### ISSUE TITLE
Unknown command: `binary-cache`

### ISSUE THREAD

**Issue by dcristolovean** [grab/cocoapods-binary-cache#13]
This step is failing for me, although I installed the gem.
Any idea why ?

 pod binary-cache --cmd=prebuild
[!] Unknown command: `binary-cache`

**Comment by trinhngocthuyen** [comment]
Hi @dcristolovean, I guess you're installing `cocoapods-binary-cache` using `bundler` (via `bundle install`). If that's the case, you should run the command with `bundle`:
```sh
bundle exec pod binary-cache --cmd=prebuild
```
Could you help try again?

**Comment by trinhngocthuyen** [comment]
This is a duplicate of https://github.com/grab/cocoapods-binary-cache/issues/12

**Comment by dcristolovean** [comment]
I don't think it is.
- no typo
- gem installed, still "unknown command'
- I have other errors when running with bundle exec, I wrote in [https://github.com/grab/cocoapods-binary-cache/issues/12](url)

**Comment by techinpark** [comment]
@dcristolovean  can you post  your `PodBinaryCacheConfig.json` file?

**Comment by dcristolovean** [comment]
Since a lot have changed it seems since last week, you can close this one and continue the discussion in a new (different) issue.
