### ISSUE TITLE
Prebuild step fails

### ISSUE THREAD

**Issue by dcristolovean** [grab/cocoapods-binary-cache#14]
I'm following the new changes since last week and ran into some issues.  (also, btw, in the Readme, installing via gemfile using tag 1.0.0 fails, it needs to be 1.0.1)

1) I installed the gem via bundle install, all OK.
2) I created a repo in my github, empty, called prebuild_frameworks, cloned if locally in the folder shown below.
3) I created the PodBinaryCacheConfig.json file:

{
  "cache_repo": "https://github.com/XXX/prebuild_frameworks.git",
  "cache_path": "~/Documents/Projects/iOS/prebuild_frameworks/"
}

4) Updated the Podfile with:

plugin "cocoapods-binary-cache"

config_cocoapods_binary_cache(
  prebuild_config: "Debug",
  dev_pods_enabled: false
)

5) So now I should start prebuilding my frameworks ? I just started with one of them, for testing purposes:
pod 'KYDrawerController', :binary => true

6) run bundle exec pod binary prebuild.  This one fails:

❯❯❯ Step: Fetching cache
Fetching cache from https://github.com/XXX/prebuild_frameworks.git (branch: master)
Cloning into '/Users/XXX/Documents/Projects/iOS/prebuilt_frameworks'...
fatal: Remote branch master not found in upstream origin
Unzipping cache: /Users/XXX/Documents/Projects/iOS/prebuild_frameworks -> Pods/_Prebuild
....
...
....
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/XXX/Documents/Projects/iOS/prebuilt_frameworks/Manifest.lock

Am I doing something wrong ?
The flow seems straighforward:   run prebuild... run push ... then  on another machine, run fetch and pod install and that's it.

**Comment by dcristolovean** [comment]
I fixed this one: 
fatal: Remote branch master not found in upstream origin, 

but it fails the same way after that.

Also, why would the "prebuild" step do a Fetching cache ?  Shouldn't prebuild just... pre build my pods and put them in the local folder, the Push would ... push them to it ?

**Comment by dcristolovean** [comment]
And another issue:

- before adding the gem, running a bundle exec pod install in my project works.
- add the gem, bundle install, bundle exec pod install now fails with this cryptic message :

[!] Invalid `Podfile` file: undefined method `empty?' for nil:NilClass.

**Comment by bigbangvn** [comment]
@dcristolovean "Also, why would the "prebuild" step do a Fetching cache ?" -> prebuild step fetches cache because it will try to do incremental build based on the current cache.

`[!] Invalid Podfile file: undefined method `empty?' for nil:NilClass.` -> can you give more logs

**Comment by pigounet-meli** [comment]
> `[!] Invalid Podfile file: undefined method `empty?' for nil:NilClass.` -> can you give more logs
> Also, did you try the example project: https://github.com/grab/cocoapods-binary-cache/tree/master/PodBinaryCacheExample

I'm having this same issue, it happened on my second application target, if i comment the target it works.

**Comment by lazyvar** [comment]
@dcristolovean I had this issue and solved it by explicitly setting `:binary => false` for any pod I didn't want to fetch a binary for. I assumed just leaving it as `pod ...` would implicitly default to `false`, but it looks it errors instead. Can't find anywhere in the source here to confirm that, but I didn't look that hard. @bigbangvn That example projects seems to have all pods as binary pods, so it wouldn't catch this issue. At least if only tested with the environment var set to true.

**Comment by lazyvar** [comment]
Addressed not the original issue, but the `[!] Invalid Podfile file: undefined method empty?' for nil:NilClass` crash in https://github.com/grab/cocoapods-binary-cache/pull/16

**Comment by namqdam** [comment]
I'm facing exactly this issue.
`No such file or directory @ rb_sysopen .cocoapods-binary-cache/prebuilt-frameworks/Manifest.lock`
Seems like this plugin delete local cache folder. I saw it appear first then it is removed.

**Comment by trinhngocthuyen** [comment]
@namqdam Sorry, I was not following up with the original issue.
About the issue in which `Manifest.lock`:
- As far as I checked, the only scenario it happens right now is when the cache repo was not properly configured. If so, when running the `prebuild` command, you shall see this failure (although it continues to execute subsequent steps):
```
Fetching cache from  (branch: master)
fatal: repository '/Users/<user>/.cocoapods-binary-cache/prebuilt-frameworks' does not exist
Unzipping cache: /Users/<user>/.cocoapods-binary-cache/prebuilt-frameworks -> _Prebuild
```

Have you set the `cache_repo` option in `configure_cocoapods_binary_cache` (refer to [this doc](https://github.com/grab/cocoapods-binary-cache/blob/master/docs/configure_cocoapods_binary_cache.md)) yet?

**Comment by namqdam** [comment]
@trinhngocthuyen thanks for fast reply. I updated my Podfile like below, then I run `pod binary prebuild`. The error appear after this step `❯❯❯ Step: Syncing cache`

`
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
use_frameworks! :linkage => :static

source 'https://github.com/CocoaPods/Specs.git'

$FirebaseSDKVersion = '6.28.1'

def is_pod_binary_cache_enabled
  ENV['POD_BINARY_CACHE_ENABLED'] == 'true'
end

if is_pod_binary_cache_enabled
  plugin "cocoapods-binary-cache"

  config_cocoapods_binary_cache(
    cache_repo: {
      "default" => {
        "remote" => "git_repo",
        "local" => "local_directory"
      },
    },
    excluded_pods: [],
    dev_pods_enabled: true,
    prebuild_config: 'Debug',
    save_cache_validation_to: "./.stats/cocoapods_binary_cache.json",
    strict_diagnosis: true
  )
end

target 'sample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Custom pods
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'react-native-camera', path: '../node_modules/react-native-camera', subspecs: [
    'BarcodeDetectorMLKit'
  ]
  pod 'Firebase/MLVision', '6.28.1'
  pod 'Firebase/MLVisionBarcodeModel', '6.28.1'
  
  pod 'RealmJS', :path => '../node_modules/realm', :binary => true
end
`

**Comment by namqdam** [comment]
![Screen Shot 2020-10-22 at 18 00 57](https://user-images.githubusercontent.com/9479593/96863117-97d38500-1490-11eb-8722-6ed4fc2169cd.png)
I see the script create a tracked local _Prebuilt dir in node_modules also. And second time this script wont run.
`Errno::ENOENT - No such file or directory @ rb_check_realpath_internal - /Users/zoop/Documents/gitlab.com/silenteer/core/hercules/node_modules/react-native/Libraries/FBLazyVector/_Prebuilt/FBLazyVector/FBLazyVector/FBLazyIterator.h`

**Comment by namqdam** [comment]
I see the script create a tracked local _Prebuilt dir in node_modules also. And second time this script wont run.
`Errno::ENOENT - No such file or directory @ rb_check_realpath_internal - node_modules/react-native/Libraries/FBLazyVector/_Prebuilt/FBLazyVector/FBLazyVector/FBLazyIterator.h`
![Screen Shot 2020-10-22 at 18 00 57](https://user-images.githubusercontent.com/9479593/96863345-f1d44a80-1490-11eb-9f3b-6b7da225329d.png)

**Comment by trinhngocthuyen** [comment]
@namqdam I think your case is different from the original issue. Also, it happens when using the plugin with development pods.
Let's take this to another thread. Could you please help report those details in another issue? Thank you!

**Comment by trinhngocthuyen** [comment]
Hi folks, let me summarize the thread here.

1/ The original issue is about the error thrown when there is no `Manifest.lock` in the cache repo. It happens for the first-time setup. This has been resolved in recent releases. Kindly try out the latest release, @dcristolovean.
In case you still encounter the issue, you can always resolve it this way:
- Pushing an empty `Manifest.lock` to the cache repo.
- Then run the `prebuild` command again.

2/ The `[!] Invalid Podfile file: undefined method empty?' for nil:NilClass` issue some encountered was fixed in https://github.com/grab/cocoapods-binary-cache/pull/17. @dcristolovean @pigounet-meli 

3/ The issue @namqdam faced can be resolved by adding `FBLazyVector` to the [`excluded_pods` option](https://github.com/grab/cocoapods-binary-cache/blob/master/docs/configure_cocoapods_binary_cache.md#excluded_pods). This is a corner case in which the plugin could not detect pods with empty sources (`*.swift`, `*.m` files)

4/ @dcristolovean's opinion about not fetching cache when running the `prebuild` command can be done by specifying the `--no-fetch` option: `bundle exec pod binary prebuild --no-fetch`

---

I'm closing this issue as this thread becomes more irrelevant to the originally reported issue (which should be resolved now).

Feel free to reach us in other relevant threads with more details.
Regards,
Thanks!
