### ISSUE TITLE
Can't push to repo with Push command

### ISSUE THREAD

**Issue by ARamy23** [grab/cocoapods-binary-cache#15]
When I write

`bundle exec pod binary push`

it looks for a branch called `Push` to *Fetch* from

shouldn't it Push the pods to it?

I use this command in the project's folder not the cache path 

thanks in advance

**Comment by christhuyenatgrab** [comment]
Hi @ARamy23, sorry. I believe there was a mistake in the doc as the `pod` command `binary push` is not currently available. Therefore, it falls back to the default command which is `binary fetch`.

The command `binary push` (if available) is just a wrapper of the three `git add`, `git commit`, and `git push` commands.

Therefore, following are some solutions to overcome this issue:

1. When prebuilding frameworks with `binary prebuild`, **specify the `--push` option**:
```sh
bundle exec pod binary prebuild --push
```
With this option, the cache will be pushed upon completion

2. OR: cd to the cache path on local and **manually push the cache**, or:

3. We shall add this command to match the documentation

**Comment by christhuyenatgrab** [comment]
The changes to add this command back was merged to master. You can check out the master branch. Yet, a new version is not released.

Usage:
```sh
bundle exec pod binary push [branch] # By default, branch is master
```

**Comment by ARamy23** [comment]
Thanks a lot

I managed to push the pods manually to a remote repo

however I'm facing a problem with building the project locally on my machine where it fails for this reason

Multiple commands produce '/Users/XXX/Library/Developer/Xcode/DerivedData/XXX-gjtjmmtpksbboffwuegnkldppsqk/Build/Products/Staging-iphonesimulator/XXX.app/gRPCCertificates-Cpp.bundle':
1) That command depends on command in Target 'XXX' (project 'XXX'): script phase “[CP] Check Pods Manifest.lock”
2) That command depends on command in Target 'XXX' (project 'XXX'): script phase “[CP] Copy Pods Resources”

is that something with the plugin?

**Comment by christhuyenatgrab** [comment]
Usually, this is not quite related to the plugin. It could be due to some project misconfiguration, or something tied with CocoaPods itself.
I guess:
- You're using [firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk) as static.
- With the current build settings, the option _Treat warnings as errors_ is currently ON. Right?

If you could share your Podfile (could be a demo project), we could help investigate more :)
Thanks

**Comment by trinhngocthuyen** [comment]
Closing the issue as the `push` command was added and the build failures above are mostly not related to cocoapods-binary-cache
