### ISSUE TITLE
arm64 Support Question

### ISSUE THREAD

**Issue by AbdulelahHajjar** [grab/cocoapods-binary-cache#19]
Hello!

I am loving this gem and it shaved a lot of time when building my app on the simulator. However when I switched to my real device when building I got warnings that the pods in the project only support x86_64 architecture as seen in the image below:

![Screen Shot 2020-08-28 at 2 35 10 PM](https://user-images.githubusercontent.com/52970044/91556641-bc512c00-e93b-11ea-8017-987b1342a9af.png)

I tried playing with the Podfile configurations provided in the "README.md" but with no luck. Also running `lipo` command on the .framework files only shows x86_64 for the pods installed.

This is the Xcode Build Command:

![Screen Shot 2020-08-28 at 2 33 38 PM](https://user-images.githubusercontent.com/52970044/91556723-dd198180-e93b-11ea-88f7-a9ad21d9c028.png)

Thanks!

**Comment by trinhngocthuyen** [comment]
Hi @AbdulelahHajjar, currently only `x86_64` is supported. This is initially to keep the cache repo thin.
The ability to specify architectures is in our plan. It should be supported soon.
Thanks.

**Comment by AbdulelahHajjar** [comment]
Hello @trinhngocthuyen,

Thank you so much for your response. I thought I made something wrong on my end and I wanted to get the most out of this gem.

I found a workaround for this issue by having 2 Podfiles in my project, one where it contains the code for the binary pods, and one where it is not.

And I call `pod deintegrate` then re-install whenever I want to change versions and it happens so smoothly, especially with Cocoapods caching where re-downloading pods is not needed as long as the cache is still not cleaned.

I find this solution to be great! And I can still enjoy using this gem while developing.

Once again, thank you so much for your response.

**Comment by trinhngocthuyen** [comment]
Hi @AbdulelahHajjar,
Kindly checkout version [0.1.5](https://github.com/grab/cocoapods-binary-cache/releases/tag/0.1.5) for the support. You can now specify the option `device_build_enabled` in `confifg_cocoapods_binary_cache` to make the prebuilt frameworks work with devices as follows:

```rb
config_cocoapods_binary_cache(
  ...
  device_build_enabled: true # <--- HERE
)
```
Do note that you need to re-build all the existing frameworks to have all the cache with device support.

**Comment by AbdulelahHajjar** [comment]
Hello @trinhngocthuyen!

This is the best news ever! I am so grateful and thankful for taking my issue into consideration, I really appreciate your hard work and the time you put into this.

I am super excited to try it out in my project.

Once again this gem has saved me a lot of time, and I thank you all for your help and support.

Yours,
Abdulelah

**Comment by AbdulelahHajjar** [comment]
Hello @trinhngocthuyen!

I have installed version 0.1.5, and I would like to confirm that it is working perfectly with my device.

Thank you so much for your help!
