### ISSUE TITLE
Script crashes/throws exception when there is no Podfile.lock in the directory

### ISSUE THREAD

**Issue by SrikanthKabadi** [grab/cocoapods-binary-cache#20]
Hi,

`lockfile.rb` script crashes at line number 9 when I am trying to do `bundle exec pod binary prebuild --push`. After struggling for a long time, realized that it is failing because it is trying to get hash of lock file and lock file does not exist in the directory.

I am on `0.1.5` version of `cocoapods-binary-cache`.

**Comment by trinhngocthuyen** [comment]
Hi @SrikanthKabadi,
Thanks for pointing out the issue. We acknowledge the issue and working on the fix.

In the meantime, to quickly resolve the issue on your end, you can try _running a normal pod installation without this plugin_ to generate the `Podfile.lock`. Then, try again with the command above.
Thanks!
