### ISSUE TITLE
I have problem when change binary from 'true' to 'false'?

### ISSUE THREAD

**Issue by nannanIT** [grab/cocoapods-binary-cache#27]
first, I use  pod 'A',  '~> 0.3.0', :binary => true,  it's ok.
but when I  change binary from 'true' to 'false', I run "bundle exec pod binary prebuild" or "pod install"
the Pods A folder has no source code.
 if I remove the Pods/ before prebuild or install, it's fine.

**Comment by trinhngocthuyen** [comment]
Hi @nannanIT, this is actually a known issue with _incremental pod installation_.
The plugin did some injections to the podspec of a pod which leads to the source files cleanup of that pod.

- If you keep it as `:binary => true`, the pod will be integrated again every time you run `pod install`.
- If you change the declaration of that pod to `:binary => false`, it's integrated as normal. But CocoaPods itself detects no change and won't do a fresh integration for that pod.
This is similar to removing a source file in a pod folder and run `pod install` again.

**Comment by nannanIT** [comment]
Thanks @trinhngocthuyen for your explanation,  got it.
But I only used **cocoapods-binary** plugin before,  and I did't encounter similar problems.
I just wonder if there are some special operations in **cocoapods-binary** plugin?

**Comment by trinhngocthuyen** [comment]
Could you please give examples of those features? Thank you!

**Comment by trinhngocthuyen** [comment]
Hi, I am closing this issue as there's little info for investigation.
Feel free to open if we have more details about the issue.
Thank you!
