### ISSUE TITLE
Why not prebuild the changed Pods file automaticly when pod install like cocoapods-binary plgin?

### ISSUE THREAD

**Issue by nannanIT** [grab/cocoapods-binary-cache#29]
When I changed the tag of a Pods file, I need run ```bundle exec pod binary prebuild```, then generate a new framework and integrate it. 
But when I use **cocoapods-binary plgin**, I only run ```pod install```, it can prebuild the changed Pods file automaticly.
So why?

**Comment by trinhngocthuyen** [comment]
Sorry, I am a bit confused as you're currently comparing 2 plugins [cocoapods-binary](https://github.com/leavez/cocoapods-binary) and this plugin (aka. [cocoapods-binary-cache](https://github.com/grab/cocoapods-binary-cache)).

Obviously, the workflows proposed by the 2 plugins would differ. With this plugin, we want to have 2 separate workflows:
- Prebuild the frameworks to deploy to the cache repo/store.
- Pod install given the prebuilt frameworks in the cache repo/store. In case of changed pods (we call it `cache miss`, just fall back to the normal integration using source code)

It's up to developers to judge the pros and cons of separating the 2 workflows or combining them into one.
