### ISSUE TITLE
Dont remove assisstants files

### ISSUE THREAD

**Issue by mefilt** [grab/cocoapods-binary-cache#30]
Hey
I have dependency FirebaseCrashlytics.
It is necessary to leave binaries or auxiliary files in dependencies.
<img width="319" alt="image" src="https://user-images.githubusercontent.com/1247906/95967285-c0b2a500-0e14-11eb-9558-cefdfb185b6c.png">

**Comment by mefilt** [comment]
Example
After then i used cashe and my folder empty :)

**Comment by mefilt** [comment]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/1247906/95968395-0d4ab000-0e16-11eb-9c21-f6011d3976ac.png">

**Comment by trinhngocthuyen** [comment]
Can you copy and store the binaries to another place in the project for your use case as of now?
We'll revise the use case and consider some support if needed.
Thanks

**Comment by mefilt** [comment]
Yeap, i did so. But is not good then files don't update in future

**Comment by trinhngocthuyen** [comment]
I've had a quick check. The `run` & `upload-symbols` binary are defined in `s. preserve_paths` of the podspec. It should be preserved while integrating with the plugin.
Shall look into it & fix this issue.
Thanks

**Comment by mefilt** [comment]
@trinhngocthuyen thx man

**Comment by trinhngocthuyen** [comment]
@mefilt you can now use the `still_download_sources` option (refer to [Configure cocoapods-binary-cache](https://github.com/grab/cocoapods-binary-cache/blob/master/docs/configure_cocoapods_binary_cache.md) to preserve the auxiliary files for `FirebaseCrashlytics`.

```rb
config_cocoapods_binary_cache(
  still_download_sources: ["FirebaseCrashlytics"]
)
```

**Comment by mefilt** [comment]
Yeee Boy! Thx Man!

**Comment by mefilt** [comment]
@trinhngocthuyen Please change version for gem update

**Comment by trinhngocthuyen** [comment]
Tag 0.1.9 has been created
