### ISSUE TITLE
Every time my cache rebuild

### ISSUE THREAD

**Issue by mefilt** [grab/cocoapods-binary-cache#34]
My flow in CI
1) Fetch from cache repo
2) Prebuild binary pods
3) Push to repository.
Every time my cache rebuild. How fix it?

**Comment by trinhngocthuyen** [comment]
I don't quite get your question. What went wrong and what is the behavior you expect?

**Comment by mefilt** [comment]
When you restart "Prebuilt"

Expecting:
Check the cache for validity and rebuild it if necessary.

On the fad:
Each time it rebuilds the cache and does not check for validity

**Comment by trinhngocthuyen** [comment]
I am assuming when referring to "validity", you mean whether there's a compatible cache for a pod.

If that's the case, we do have that in place. By default, the plugin **only prebuilds pods detected as cache miss** (ie. pods having no compatible cache) unless you specify the `--all` option in the `prebuild` command.

**Comment by mefilt** [comment]
Some modules which are detected as cache misses every time

**Comment by trinhngocthuyen** [comment]
Could you please elaborate more details on such cases? And it would be best if we have a demo project for investigation.

**Comment by trinhngocthuyen** [comment]
Hi, I am closing this issue as there's little info for investigation.
Feel free to re-open if we have more details about the issue.
Thank you!

**Comment by sseen** [comment]
@trinhngocthuyen I also encountered this problem in CircleCI. 
**Local is no problem, only ci has this problem.**

I found all pod excluded using the cache, Instead, all the other packages were re-downloaded from cocoapods cdn.
Some of the logs are as follows.

<img width="401" alt="截屏2021-12-01 下午5 43 40" src="https://user-images.githubusercontent.com/3367000/144212167-426eebcd-0d0d-4a36-b129-afdc9c6b685a.png">


<img width="588" alt="截屏2021-12-01 下午5 47 28" src="https://user-images.githubusercontent.com/3367000/144212225-86430bbc-4f1b-4ebd-9f7e-999087e926e4.png">

<img width="502" alt="截屏2021-12-01 下午5 49 54" src="https://user-images.githubusercontent.com/3367000/144212254-88e0c64a-e42f-4744-a486-fd7dfca2fb0d.png">

Expected to download from the cache, but here from cocoapods cdn.
