### ISSUE TITLE
feature request: support :all_binary! flag

### ISSUE THREAD

**Issue by cnadeau** [grab/cocoapods-binary-cache#35]
same flag as [cocoapods-binary](https://github.com/leavez/cocoapods-binary#usage) which sets :binary => true to all pods and we only have to set :binary => false on those who we do not want to cache

**Comment by trinhngocthuyen** [comment]
Thanks for reaching out!

We'll evaluate this request and keep you posted with the update.
In the meantime, I would like to give a few other suggestions:

**Suggestion 1:** Define a helper function, for ex. `binary_pod`, that has the `:binary` option enabled. Then use it when declaring pods.

**Suggestion 2:** Patch the pod declaration and decorate the pod requirements with the `:binary` option:
(the following code block can be placed at the top of Podfile)
```rb
module Pod
  class Podfile
    module DSL
      alias original_pod pod
      def pod(name = nil, *requirements)
        original_pod(name, *decorate_requirements(name, *requirements))
      end

      def decorate_requirements(name = nil, *requirements)
        requirements << {} unless requirements.last.is_a?(Hash)
        kwargs = requirements.last
        kwargs[:binary] = true if kwargs[:binary].nil? # <--- Set to true unless explicitly set
        requirements
      end
  end
end
```

**Comment by cnadeau** [comment]
This is a nice workaround, thanks!

**Comment by claybridges** [comment]
Did this ever happen?

**Comment by haifengkao** [comment]
I have to use the following code in Podfile for cocoapods 1.10
```ruby
    module DSL
      alias :original_pod :pod
      def pod(name = nil, *requirements)
        original_pod(name, *decorate_requirements(name, *requirements))
      end

      def decorate_requirements(name = nil, *requirements)
        requirements << {} unless requirements.last.is_a?(Hash)
        kwargs = requirements.last
        kwargs[:binary] = true if kwargs[:binary].nil? # <--- Set to true unless explicitly set
        requirements
      end
    end
```

**Comment by acshi** [comment]
I had a slight difficulty getting this workaround running because I misunderstood haifengkao's statement. The important thing was removing the outer module Pod and class Podfile, not just adding the colons to the alias line.
