### ISSUE TITLE
Feature Request: remote branch name per configuration

### ISSUE THREAD

**Issue by cnadeau** [grab/cocoapods-binary-cache#38]
I'd like to know if it's possible to set the branch in the configuration from the Podfile to get something like:

```
config_cocoapods_binary_cache(
  cache_repo: {
    "default" => {
      "remote" => "git@cache_repo.git",
      "remote_branch" => "all_pods",  <<<<<<<
      "local" => "~/.cocoapods-binary-cache/prebuilt-frameworks"
    }
  },
  prebuild_config: "Debug"
)
```

We have an app that dictates the dependencies of 9 other internal pods. I'd love to build once from the app and be able to do something like

```bash
cd app
pod binary prebuild --push app_version
cd ../my_sub_pod 
pod binary fetch app_version 
pod install # to cleanup all unused cached pods
pod binary push my_sub_pod # update all cached pods for a specific sdk
```

Would it be something possible?

**Comment by trinhngocthuyen** [comment]
Hi @cnadeau,
Currently, we do support custom cache branches. The cache branch (default as `master`) can be passed via the CLI of the `fetch`, `push`, and `prebuild` commands. For example:
```sh
bundle exec pod binary fetch cache_branch_goes_here
```
For more details about what options supported in the CLI, kindly pass `--help` to the given commands, for ex. `bundle exec pod binary prebuild --help`.

**Comment by cnadeau** [comment]
Thanks @trinhngocthuyen, thanks for the quick reply. This is exactly what I'm currently doing, but I would love to get it more automated

@trinhngocthuyen How would you implement that configuration it in the codebase? I might have some time to help again to get that feature in if you guide me on how you would architecture it within the project

Thanks again

**Comment by trinhngocthuyen** [comment]
> ```
> cd app
> pod binary prebuild --push app_version
> cd ../my_sub_pod 
> pod binary fetch app_version 
> pod install # to cleanup all unused cached pods
> pod binary push my_sub_pod # update all cached pods for a specific sdk
> ```

Sorry, I think I'm a little confused by the request.
Do you mean you want to **prebuild & push certain frameworks**, not all of them? If so, you could use the `--targets` option in the prebuild CLI, like this: `bundle exec pod binary prebuild --targets=A,B,C`

**Comment by cnadeau** [comment]
The usage would be the same pods for several projects and what I had in mind is a simplified vision of 
@savage7 https://github.com/grab/cocoapods-binary-cache/issues/62 feature request because we have several frameworks depending on each other

Root => A => B => C

and A, B and C have their own CDN dependencies

The Root cache can be used to build A, B and C for CI Unit tests validation since it contains all the required frameworks

And the `--targets` options seems to be the part I missed to actually prebuild a release version of the framework using the cache. Thanks again!
