### ISSUE TITLE
ModuleNotFoundError: No module named 'colorlog'

### ISSUE THREAD

**Issue by qalandarov** [grab/cocoapods-binary-cache#4]
Seems like `colorlog` has to be installed before running the python scripts as `import colorlog` on `logger.py` fails

**Comment by trinhngocthuyen** [comment]
Oh, right. I'll submit a change to make this package import optional. In the meantime, you can [install this Python package](https://packaging.python.org/tutorials/installing-packages/), perhaps via pip:
```sh
python3 -m pip install colorlog
```

**Comment by qalandarov** [comment]
Thanks for the quick response! I already installed it, just wanted to bring it to your attention

**Comment by trinhngocthuyen** [comment]
Cool! The issue should be resolved in https://github.com/grab/cocoapods-binary-cache/commit/f159cbfeecf8d5eb7f05937598a6fc2f19c0a7c2.
Thanks!
