### ISSUE TITLE
Support Project & Cache Paths with Space

### ISSUE THREAD

**Issue by VaslD** [grab/cocoapods-binary-cache#40]
Please properly quote project and cache paths in `git` and `xcodebuild` commands to support project and cache paths with space and other special characters. It's 2020.

Currently, `pod binary prebuild --push` fails with "*fatal: Too many arguments.*" when executing `git` if cache path contains space; and with "*RuntimeError - Fail to build targets*" when executing `xcodebuild` if Xcode project folder contains space.

I hope I'm not asking too much because interestingly alternatives to this *cocoapods-binary-cache* also suffer from this issue. I don't know if Ruby does it differently or is more complicated to deal with, but quoting paths is like rule No. 1 of programming.

**Comment by trinhngocthuyen** [comment]
Hi @VaslD,
Thanks for reaching out! I have fixed the escaped path in https://github.com/grab/cocoapods-binary-cache/commit/95091be7b1cf920b9d72fb5e7b6ba126560aa893 but have not yet released a new version then.
Note that theis fix targets specifically `xcodebuild` arguments. I haven't checked other workflows :).

Of course, we'll try to handle the spacings issue.
However, I personally think It would be best if you can get rid of spacings in the directory as there are many external dependencies (other plugins, for example) out there that do not handle this yet.

**Comment by VaslD** [comment]
Thank you for the quick response.

I'll check out the commit you mentioned. I'm fairly certain that Git pull/push phases also have issues dealing with special characters in path. Since you were already aware of the issue I'll close this for now.
