### ISSUE TITLE
How to completely clear local cache and compile pods

### ISSUE THREAD

**Issue by matumba123** [grab/cocoapods-binary-cache#47]
How to completely clear local cache and compile pods with xcodebuild ? I delete all cache folders, but xcodebuild doesn't work. It doesn't even get called

**Comment by trinhngocthuyen** [comment]
Hi there,
I am assuming that by "local cache", you mean prebuilt frameworks and files/dirs managed by the plugin.
If you wish to do clean them up:
- `rm -rf Pods _Prebuild _Prebuild_delta ~/.cocoapods-binary-cache`
