### ISSUE TITLE
Switch from binary mode to code mode, it doesn't work well

### ISSUE THREAD

**Issue by DJean** [grab/cocoapods-binary-cache#48]
Hi, when I want debug and switch binary mode to code mode, I tried set `:binary=>false` or remove `plugin 'cocoapods-binary-cache'`, only **Development Pods** works. But **RxSwift** or **Alamofire** always framework. Now I only use `rm -rf Pods` can go well, it's my config issue?

**Comment by trinhngocthuyen** [comment]
Hi. @DJean, to give you a brief explanation:

The plugin modifies pod directory contents in the sandbox. So, if you use `:binary => true`, it works normally. When switching from `:binary => true` to `:binary => false`, it does not work properly with *incremental installation* as some source files are cleaned up in the previous run.

The same issue happens in a normal installation (without the plugin) if you delete some files in the sandbox before running pod install. So, I would say it's not really an issue.

My suggestion: when switching `:binary => true` to `:binary => false` to debug a pod X, you should delete `Pods/X`
