### ISSUE TITLE
[CP] Embed Pods Frameworks fails when Archiving

### ISSUE THREAD

**Issue by spencerdiniz** [grab/cocoapods-binary-cache#49]
### Checklist

- [x] Updated the plugin to the latest version
- [x] I've read the [Contribution Guidelines](https://github.com/grab/cocoapods-binary-cache/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/grab/cocoapods-binary-cache/issues)

### Issue Description
I'm attempting to use cocoapods-binary-cache in my project, but I'm having a problem archiving to app when using it.
The app builds and runs successfully, but archiving fails. There's an execution error for the **[CP] Embed Pods Frameworks** script. See bellow:

<pre>
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/spencerdiniz/Library/Developer/Xcode/DerivedData/Pixie-fyzwsjbzhfhiwrciwvfjfhfuzudr/Build/Intermediates.noindex/ArchiveIntermediates/Global\ TestFlight/IntermediateBuildFilesPath/Pixie.build/Debug-iphoneos/Pixsee\ Global.build/Script-E3CF3E6BE471CF8384D698BC.sh (in target 'Pixsee Global' from project 'Pixie')
    cd /Users/spencerdiniz/Work/Venturus/SourceCode/ios
    /bin/sh -c /Users/spencerdiniz/Library/Developer/Xcode/DerivedData/Pixie-fyzwsjbzhfhiwrciwvfjfhfuzudr/Build/Intermediates.noindex/ArchiveIntermediates/Global\\\ TestFlight/IntermediateBuildFilesPath/Pixie.build/Debug-iphoneos/Pixsee\\\ Global.build/Script-E3CF3E6BE471CF8384D698BC.sh

mkdir -p /Users/spencerdiniz/Library/Developer/Xcode/DerivedData/Pixie-fyzwsjbzhfhiwrciwvfjfhfuzudr/Build/Intermediates.noindex/ArchiveIntermediates/Global TestFlight/BuildProductsPath/Debug-iphoneos/Pixsee Global.app/Frameworks
Symlinked...
Command PhaseScriptExecution failed with a nonzero exit code
</pre>

Any help would be greatly appreciated. 

#### Plugin version
0.1.11

#### Installed CocoaPods plugins
<details><pre>
Installed CocoaPods Plugins:
    - cocoapods-binary-cache : 0.1.11 (pre_install and post_install hooks)
    - cocoapods-deintegrate  : 1.0.4
    - cocoapods-plugins      : 1.0.0
    - cocoapods-search       : 1.0.0
    - cocoapods-stats        : 1.1.0 (post_install hook)
    - cocoapods-trunk        : 1.5.0
    - cocoapods-try          : 1.2.0
</pre></details>

**Comment by kientux** [comment]
Anyone facing this problem can checkout this issue for a temporary workaround: https://github.com/CocoaPods/CocoaPods/issues/10298

**Comment by sdiniz-truelogic** [comment]
Thanks for suggestion. I’ll give it a try and report back.

**Comment by thomaswinkler** [comment]
@sdiniz-truelogic, see my comment/fix https://github.com/CocoaPods/CocoaPods/issues/10298#issuecomment-779455634. I found it to be missing path escaping in the readlink() wrapper implementation cocoapods-binary is adding. If your project name contains spaces, you will run into this issue.

**Comment by rogerluan** [comment]
@spencerdiniz I just opened a PR that should fix your issue 💪

**Comment by sdiniz-truelogic** [comment]
> @spencerdiniz I just opened a PR that should fix your issue 💪

Nice! Thanks.

**Comment by kevalgplutus** [comment]
I am facing below error while trying to run fastlane lanes from jenkins but the flow is working fine with local terminal

`PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/jenkins/Library/Developer/Xcode/DerivedData/CDC-bzswrvazlutuhkeafnfspzbueoaa/Build/Intermediates.noindex/ArchiveIntermediates/WLA/IntermediateBuildFilesPath/CDC.build/WLA-iphoneos/CDC.build/Script-B8G2C0E378AF1A9BCC158ACE2.sh (in target 'CDC' from project 'CDC')
`
Any help would be appreciated 
Thanks

**Comment by DodoSpringLove** [comment]
> 

The same goes for you

**Comment by umang2203** [comment]
I am facing similar issue

```
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Volumes/Workspace/jenkins/workspace/MyGame-Prod-iOS/bin/app/game/build/iphone/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Script-D35EE720B184DEA10D74350E.sh (in target 'Unity-iPhone' from project 'Unity-iPhone')
    cd /Volumes/Workspace/jenkins/workspace/Test/MyGame-Prod-iOS/bin/app/game/build/iphone/src
    /bin/sh -c /Volumes/Workspace/jenkins/workspace/Test/MyGame-Prod-iOS/bin/app/game/build/iphone/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/IntermediateBuildFilesPath/Unity-iPhone.build/Release-iphoneos/Unity-iPhone.build/Script-D35EE720B184DEA10D74350E.sh
mkdir -p /Volumes/Workspace/jenkins/workspace/Test/MyGame-Prod-iOS/bin/app/game/build/iphone/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/Unity-iPhone/BuildProductsPath/Release-iphoneos/MyGame.app/Frameworks
Symlinked...
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by amanbabbar-kipl** [comment]
I am running Fastlane on the Mac agent node with the Jenkins controller and facing the same issue.

The following build commands failed:
16:24:29  	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/macstudio/Library/Developer/Xcode/DerivedData/brandvox-ckdfytqcvospulgotnphrsyjlrdl/Build/Intermediates.noindex/ArchiveIntermediates/brandvox/IntermediateBuildFilesPath/brandvox.build/Release-iphoneos/brandvox.build/Script-00EEFC60759A1932668264C0.sh


Command PhaseScriptExecution failed with a nonzero exit code

Did anyone found the solution?

**Comment by gitgobrr** [comment]
For me this small adjustment helped:
Go to ${PODS_ROOT}"/Target Support Files/Pods-AppName/Pods-AppName-frameworks.sh"
Line 42 in my file: 
```
  if [ -L "${source}" ]; then
    echo "Symlinked..."
    source="$(readlink -f "${source}")" # add "-f" option to the readlink command
  fi
```

**Comment by closure11** [comment]
For anyone still facing the `Command PhaseScriptExecution failed with a nonzero exit code` issue after updating CocoaPods 1.12.1:

CocoaPods has [added the -f option when resolving the path to the symlinked source](https://github.com/CocoaPods/CocoaPods/pull/11828), which makes this overridden `readlink` function broken. 

https://github.com/grab/cocoapods-binary-cache/blob/f85630964fa5fde96239fe97a769e4c3160e443d/lib/cocoapods-binary-cache/pod-binary/integration/patch/embed_framework_script.rb#L18-L20

This code expects the first argument `$1` to be a file path, but now it's actually `-f`:

```shell
  # Pods-MyApp-frameworks.sh
  if [ -L "${source}" ]; then
    echo "Symlinked..."
    source="$(readlink -f "${source}")"
  fi

```

Can the maintainer fix this please?

### What's more
Some comments in CocoaPods issues said changing `readlink -f "${source}"` to `greadlink -f "${source}"`, if this issue can't be solved with the `readlink -f` command.

This `greadlink` did solve the problem, but at the time I didn't realize why it works, and why the vast majority of other people didn't need to do it. Now I find that it has to do with cocoapods-binary-cache.

**Comment by lucasromanomr** [comment]
I'm having the same problem currently using Xcode 15.4

**Comment by xuweixi11** [comment]
> I'm having the same problem currently using Xcode 15.4

cocoapods-binary-cache-next 0.1.16 maybe slove this
