### ISSUE TITLE
Fails if there're no dev pods

### ISSUE THREAD

**Issue by qalandarov** [grab/cocoapods-binary-cache#5]
If you remove any of these keys: `devpod_cache_repo` / `devpod_cache_repo` / `devpod_prebuild_output` then `prebuild_config.py` fails because we're getting the keys with `config['devpod_cache_path']` instead of `config.get('devpod_cache_path')`

Also, if your Podfile doesn't have a dev pod then this fails: `prebuild_cache.rb:89:in `get_dev_pods'`

**Comment by trinhngocthuyen** [comment]
> Also, if your Podfile doesn't have a dev pod then this fails: prebuild_cache.rb:89:in `get_dev_pods'`

Good spot 😄 ! We shall revise the code again for this particular scenario (when there is no development pod).

Thanks!

**Comment by qalandarov** [comment]
That could be because of having this flag `enable_devpod_prebuild` and not having the dev pods

**Comment by lixiaoyu** [comment]
I meet this issues too, the error message is like 
`NoMethodError - undefined method `each' for nil:NilClass
/Users/xx/Desktop/cocoapods-binary-cache/lib/cocoapods-binary-cache/prebuild_cache.rb:90:in `get_dev_pods'
/Users/xx/Desktop/cocoapods-binary-cache/lib/cocoapods-binary-cache/prebuild_cache.rb:68:in `verify_prebuilt_vendor_pods'`

i added a check for dev_pods

**Comment by trinhngocthuyen** [comment]
Could you help remove `enable_prebuild_dev_pod` in Podfile and try again?
Let's not use this flag if there is no development pod in the project
