### ISSUE TITLE
I delete some files, but after prebuild，the file is still in framework headers directory

### ISSUE THREAD

**Issue by ruzhuxiaogu** [grab/cocoapods-binary-cache#50]
I delete some files, but after prebuild，the file is still in framework headers directory

**Comment by trinhngocthuyen** [comment]
Could you please provide some more details about the issue?
Thank you!

**Comment by ruzhuxiaogu** [comment]
> Could you please provide some more details about the issue?
> Thank you!

thank you for your reply, when I clean git clean, and rebuild, the problem fixed!
