### ISSUE TITLE
I only succeeded for the first time, when I add more pods in my project, it can not prebuild frameworks

### ISSUE THREAD

**Issue by yusheng00** [grab/cocoapods-binary-cache#52]
### Checklist

- [ ] Updated the plugin to the latest version
- [ ] I've read the [Contribution Guidelines](https://github.com/grab/cocoapods-binary-cache/blob/master/CONTRIBUTING.md)
- [ ] I've searched for [existing GitHub issues](https://github.com/grab/cocoapods-binary-cache/issues)

#### Command executed

<details><pre>[Details go here]</pre></details>

#### What went wrong?

Prebuild frameworks (total 0): []
No changes in prebuild

but i add another pod 

#### Stack trace

<details><pre>[Details go here]</pre></details>

#### Plugin version

<details><pre>[Details go here]</pre></details>

#### Installed CocoaPods plugins

<details><pre>[Details go here]</pre></details>

**Comment by trinhngocthuyen** [comment]
Could you please provide some more details about the issue for investigation?
Thank you!
