### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by kientux** [grab/cocoapods-binary-cache#54]
### Checklist

- [x] Updated the plugin to the latest version
- [x] I've read the [Contribution Guidelines](https://github.com/grab/cocoapods-binary-cache/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/grab/cocoapods-binary-cache/issues)

### Issue Description
This plugin builds pods into fat `.framework` binary which is not supported anymore on Xcode 12 (and Apple Silicon when build on simulator). Is there anyway to build `xcframework` instead?

```
Module 'NVActivityIndicatorView' was created for incompatible target arm64-apple-ios9.0:
.../Pods/NVActivityIndicatorView/_Prebuilt/NVActivityIndicatorView.framework/Modules/NVActivityIndicatorView.swiftmodule/arm64.swiftmodule
```

#### Command executed

```sh
$ bundle exec pod binary prebuild
```

#### Configuration
```ruby
config_cocoapods_binary_cache(
  cache_repo: {
    "default" => {
      "local" => "~/.cocoapods-binary-cache/prebuilt-frameworks"
    }
  },
  prebuild_config: "Debug",
  device_build_enabled: true
)
```

**Comment by trinhngocthuyen** [comment]
Thanks for reaching out and reporting the issue.
We shall revise this logic with Xcode 12 and explore some alternatives to overcome this problem.
Will keep you updated on this. Thanks!

**Comment by innocarpe** [comment]
I had an same issue. Hope this will be fixed soon 🙏 Appreciated.

**Comment by trinhngocthuyen** [comment]
I'd like to confirm that the issue occurs when running on ARM-based macs and the prebuilt frameworks are targeted for both simulators and devices.

We currently have difficulty testing with ARM-based macs (both on local and on CI) in order to explore other options. Therefore, for now, we're gonna go ahead with the support for `xcframework` as suggested.

**Contract**: There will be an option in the configuration to use to `xcframework` instead of creating the fat binary:
```rb
config_cocoapods_binary_cache(
  ...
  xcframework: true
)
```
Will notify you here once the support is available.
Thanks for the suggestion.

**Comment by trinhngocthuyen** [comment]
Hi @kientux, the support for `xcframework` is included in https://github.com/grab/cocoapods-binary-cache/commit/3f700904324e8fe3d5857b57d2ce43b1b5d080f3.
Kindly check out the [`xcframework` option](https://github.com/grab/cocoapods-binary-cache/blob/master/docs/configure_cocoapods_binary_cache.md#xcframework) and let us know if it resolves your issue.
Thank you!

**Comment by kientux** [comment]
First, thank you for your fast response and support!

I can't get it to work though, with this configuration (on a fresh project):

```ruby
plugin "cocoapods-binary-cache"

config_cocoapods_binary_cache(
  cache_repo: {
    "default" => {
      "local" => "~/.cocoapods-binary-cache/prebuilt-frameworks"
    }
  },
  prebuild_config: "Debug",
  xcframework: true
)

target 'TestCocoaPodsBinaryCache' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestCocoaPodsBinaryCache
  pod 'Charts', :binary => true

end
```

First, this build error pops up:

```
Multiple commands produce '/Users/kientux/Library/Developer/Xcode/DerivedData/TestCocoaPodsBinaryCache-btqicwbpgkdajfdpakqzjxetlcws/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Charts':
1) That command depends on command in Target 'Charts' (project 'Pods'): script phase “[CP] Copy XCFrameworks”
2) That command depends on command in Target 'Charts' (project 'Pods'): script phase “[CP] Copy XCFrameworks”

============
Multiple commands produce '/Users/kientux/Library/Developer/Xcode/DerivedData/TestCocoaPodsBinaryCache-btqicwbpgkdajfdpakqzjxetlcws/Build/Products/Debug-iphonesimulator/TestCocoaPodsBinaryCache.app/Frameworks/Charts.framework':
1) That command depends on command in Target 'TestCocoaPodsBinaryCache' (project 'TestCocoaPodsBinaryCache'): script phase “[CP] Embed Pods Frameworks”
2) That command depends on command in Target 'TestCocoaPodsBinaryCache' (project 'TestCocoaPodsBinaryCache'): script phase “[CP] Embed Pods Frameworks”
```

And I actually see duplicated lines in build phase scripts:
- In “[CP] Copy XCFrameworks” of Pods project:

```sh
install_xcframework "${PODS_ROOT}/Charts/_Prebuilt/Charts.xcframework" "Charts" "framework" "ios-x86_64-simulator"
install_xcframework "${PODS_ROOT}/Charts/_Prebuilt/Charts.xcframework" "Charts" "framework" "ios-x86_64-simulator"
```
- In “[CP] Embed Pods Frameworks” of main project:
```sh
if [[ "$CONFIGURATION" == "Debug" ]]; then
  install_framework "${PODS_XCFRAMEWORKS_BUILD_DIR}/Charts/Charts.framework"
  install_framework "${PODS_XCFRAMEWORKS_BUILD_DIR}/Charts/Charts.framework"
fi
if [[ "$CONFIGURATION" == "Release" ]]; then
  install_framework "${PODS_XCFRAMEWORKS_BUILD_DIR}/Charts/Charts.framework"
  install_framework "${PODS_XCFRAMEWORKS_BUILD_DIR}/Charts/Charts.framework"
fi
```

and also there are duplicated lines in `input-files.xcfilelist`, `output-files.xcfilelist` of those build phases.

After manually remove all duplicated lines, that build error is gone. But there's other one:

```
ld: warning: directory not found for option '-F/Users/kientux/Library/Developer/Xcode/DerivedData/TestCocoaPodsBinaryCache-btqicwbpgkdajfdpakqzjxetlcws/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Charts'
ld: framework not found Charts
```

At the same time, this warning appears in “[CP] Copy XCFrameworks” phase:
```
warning: [CP] Unable to find matching .xcframework slice in '/Users/kientux/devs/TestCocoaPodsBinaryCache/Pods/Charts/_Prebuilt/Charts.xcframework Charts framework ios-x86_64-simulator' for the current build architectures (arm64).
```

Is there something wrong with the build process of xcframework?

**Comment by trinhngocthuyen** [comment]
It seems like you're trying to use the prebuilt frameworks for devices.
> warning: [CP] Unable to find matching .xcframework slice in '/Users/kientux/devs/TestCocoaPodsBinaryCache/Pods/Charts/_Prebuilt/Charts.xcframework Charts framework ios-x86_64-simulator' for the current build architectures (arm64).

--> In order to support devices architecture in the framework, you need to enable the [`device_build_enabled`](https://github.com/grab/cocoapods-binary-cache/blob/master/docs/configure_cocoapods_binary_cache.md#device_build_enabled) option. Otherwise, the prebuilt frameworks can be only used for simulators.

It was a bit weird that there are duplications in the `input-files.xcfilelist` as this logic is taken care of by CocoaPods. But let's see if the issue is resolved after you enable the `device_build_enabled` or not.

**Comment by kientux** [comment]
After enable `device_build_enabled` option, this error still persists:

```
[CP] Unable to find matching .xcframework slice in '/Users/kientux/devs/TestCocoaPodsBinaryCache/Pods/Charts/_Prebuilt/Charts.xcframework Charts framework ios-x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64).
```

The path in that message seems weird isn't it? Maybe the copy phase is not right.

I can confirm that the output framework in `_Prebuild` is successfully built for arm64:

```sh
$ file Charts.framework/Charts
Charts.framework/Charts: Mach-O universal binary with 2 architectures: [arm_v7:Mach-O dynamically linked shared library arm_v7] [arm64]
Charts.framework/Charts (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
Charts.framework/Charts (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

**Comment by trinhngocthuyen** [comment]
I figured out the cause. It occurs when we use a pod that has subspecs. It's more like CocoaPods issue:
- When we declare an `.xcframework` as a vendor framework in each subspec, we got the duplicates as above.
- Meanwhile, it's not the case when declaring a `.framework` as a vendor framework.
Anw, we'll try to fix it from our side.

**Comment by trinhngocthuyen** [comment]
Hi @kientux, the fix should be available now. Kindly check the latest on master (since https://github.com/grab/cocoapods-binary-cache/commit/82b9246ac8355b0228422d277c0d649e37aa9137).
Also, you can find the demo project with xcframework in this link https://github.com/trinhngocthuyen/troubleshoot-pod-bin-cache/tree/master/issue-54.

**Comment by kientux** [comment]
Hmm.. The fix is working for Intel mac, and it successfully builds project with xcframework inside Pods project. But it's not working for ARM mac, cannot find the framework.

```
warning: [CP] Unable to find matching .xcframework slice in '/Users/kientux/devs/troubleshoot-pod-bin-cache/issue-54/Pods/Charts/_Prebuilt/Charts.xcframework Charts framework ios-x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64).
```

After add some logs into the copy framework scripts of pods project, I found out that the problem is, copy scripts is looking for `simulator` slice inside xcframework, and it thinks that simulator slice should contains "simulator" in name. The xcframework produces 2 framework: `ios-arm64_armv7` and `ios-x86_64-simulator`, hence the script will try to use the later one. Then it checks for current build architecture (in this case is `arm64` - simulator on ARM mac) and it fails because the framework is x86_64.

```sh
      # This regex matches all possible variants of the arch in the folder name:
      # Let's say the folder name is: ios-armv7_armv7s_arm64_arm64e/CoconutLib.framework
      # We match the following: -armv7_, _armv7s_, _arm64_ and _arm64e/.
      # If we have a specific variant: ios-i386_x86_64-simulator/CoconutLib.framework
      # We match the following: -i386_ and _x86_64-
      # When the .xcframework wraps a static library, the folder name does not include
      # any .framework. In that case, the folder name can be: ios-arm64_armv7
      # We also match _armv7$ to handle that case.
      local target_arch_regex="[_\-]${target_arch}([\/_\-]|$)"
      echo "target_arch: ${target_arch}"
      if ! [[ "${paths[$i]}" =~ $target_arch_regex ]]; then
        echo "third check: matched_all_archs set to 0"
        matched_all_archs="0"
        break
      fi

....
    # this will be fail
    if [[ "$matched_all_archs" == "1" ]]; then
      # Found a matching slice
      echo "Selected xcframework slice ${paths[$i]}"
      SELECT_SLICE_RETVAL=${paths[$i]}
      break
    fi
```

So, I think this is something that CocoaPods should fixes, isn't it? One way we can do on our side is rename the output of framework slice, but that's an ugly hack and need some ugly checks as well.

**Comment by kientux** [comment]
This is how `Carthage` produces the xcframework:

```sh
$ tree -L 1 Charts.xcframework
Charts.xcframework
├── Info.plist
├── ios-arm64_armv7
└── ios-arm64_i386_x86_64-simulator
```

It includes the `arm64` in name of simulator slice. So maybe this line in your build script is where causes the problem?

```ruby
args_[:simulator] += ["ARCHS=x86_64", "ONLY_ACTIVE_ARCH=NO"] if simulator == "iphonesimulator"
```

**Comment by trinhngocthuyen** [comment]
Thank you for looking into the code to troubleshoot the issue.
I forgot that the `x86_64` is an Intel-based arch, and hence, the default build arguments should not have `ARCHS=x86_64` when building for simulators in this case.
TBH, I don't have an M1 machine to test my change thoroughly 😄. It would be great if you can give us a hand trying out this:
- There is an undocumented option called `build_args` in the `config_cocoapods_binary_cache` that is used to customize `xcodebuild` arguments when building frameworks for simulators and devices.
```rb
config_cocoapods_binary_cache(
  ...
  build_args: {
    :simulator => [
      "ARCHS='x86_64 arm64'" # or "ARCHS=arm64", I'm assuming the default simulator arch on M1 mac is arm64
    ]
  }
)
```
- Please use the following commit https://github.com/grab/cocoapods-binary-cache/commit/805aa7f09a062e0aa6c7d6cae2e33a65ff885fc9. It makes the `build_args` have higher priority than the default arguments. Please don't panic if you see there are 2 arguments `ARCHS=x86_64 ARCHS='x86_64 arm64'` in the `xcodebuild` command. Only the latter matters.

Thanks for the collaboration!

**Comment by kientux** [comment]
Oookay so finally it worked! Thank you for making this wonderful plugin!

**Comment by kientux** [comment]
Um I'm gonna reopen this because there is a problem with framework which name of the module is the same as name of its class. For example, `NVActivityIndicatorView` framework has its main class name is also `NVActivityIndicatorView`.

Here's the generated framework module files:

```sh
NVActivityIndicatorView.framework/Modules/NVActivityIndicatorView.swiftmodule
├── Project
├── arm.swiftdoc
├── arm.swiftinterface
├── arm64-apple-ios.swiftdoc
├── arm64-apple-ios.swiftinterface
├── arm64.swiftdoc
├── arm64.swiftinterface
├── armv7-apple-ios.swiftdoc
├── armv7-apple-ios.swiftinterface
├── armv7.swiftdoc
└── armv7.swiftinterface
```

As you see, only the `.swiftinterface` is generated. And then when build the project, a lot of these errors appear inside of `.swiftinterface` file:
 
```
public static func == (a: NVActivityIndicatorView.NVActivityIndicatorType, b: NVActivityIndicatorView.NVActivityIndicatorType) -> Swift.Bool
                                                  ^
'NVActivityIndicatorType' is not a member type of 'NVActivityIndicatorView'
```

When I look into `Carthage` version of xcframework, it doesn't have the `swiftinterface` files but only `swiftmodule` files. And actually they use this flag when create xcframework:

```sh
$ xcodebuild -create-xcframework -allow-internal-distribution
```

In `xcodebuild` help page:

> -allow-internal-distribution    Specifies that the created xcframework contains information not suitable for public distribution.

I tried that and the generated xcframework will contains **both** `.swiftinterface` and `.swiftmodule` files.

```sh
Charts.framework/Modules/Charts.swiftmodule
├── arm.swiftdoc
├── arm.swiftinterface
├── arm.swiftmodule
├── arm64-apple-ios.swiftdoc
├── arm64-apple-ios.swiftinterface
├── arm64-apple-ios.swiftmodule
├── arm64.swiftdoc
├── arm64.swiftinterface
├── arm64.swiftmodule
├── armv7-apple-ios.swiftdoc
├── armv7-apple-ios.swiftinterface
├── armv7-apple-ios.swiftmodule
├── armv7.swiftdoc
├── armv7.swiftinterface
└── armv7.swiftmodule
```
Don't know why Carthage version doesn't have `.swiftinterface`, maybe they removed them after that, but anyway, with `.swiftmodule` files, those errors disappear and the project is successfully built.

So can you add this flag when create the xcframework?

And `-create-xcframework` has the option to include debug symbols, maybe you can support it as well, but that should be in another issue I think.

**Comment by trinhngocthuyen** [comment]
I've made the update in https://github.com/grab/cocoapods-binary-cache/commit/b18577b3c8b7a7396c6201033b521a9488c6d817.

The `.swiftinterface` is generated when we enable library evolution (aka. module stability) which is required to create an `xcframework`. With library evolution enabled, it's a known issue of Swift that the `swiftinterface` generation is not correct if a struct/class/enum name is identical to the module name.
When using the `-allow-internal-distribution` flag, it's possible to create an xcframework without library evolution. Thanks for the info 👍!

**Comment by kientux** [comment]
Oh so `BUILD_LIBRARY_FOR_DISTRIBUTION` flag is the one generated swiftinterface! Thanks for your greate support as usual!

**Comment by kientux** [comment]
When archive project with binary cached enabled (not sure if `xcframework` option affects or not), CocoaPods `[CP] Embed Pod frameworks`  build phase is failed, caused by something related to symlinked frameworks. I see that cocoapods-binary-cache use frameworks symlinks alot, so if anyone facing this problem, checkout this CocoaPods issue for temporary workaround: https://github.com/CocoaPods/CocoaPods/issues/10298

**Comment by trinhngocthuyen** [comment]
It could be a duplicate of https://github.com/grab/cocoapods-binary-cache/issues/49.
If that's the case, please help continue the relevant discussion in that thread with more details for troubleshooting.
For now, shall we close this issue?

**Comment by kientux** [comment]
Yes it's exactly #49
Let close this now

**Comment by savage7** [comment]
@trinhngocthuyen 
Wouldn't be easier not to "ARCHS=" at all. In this case XCode creates all simulator slices which exist:
x86_64 i386 arm64

This seams to be more robust. 

We have mixed env, with developers having m1 and x86 macs, always setting build_args manually seams error prone. 
Also if you choose a 32bit simulator this leads currently to an error that "i386" is missing.

**Comment by trinhngocthuyen** [comment]
It's true that this (default) setting should not be present in the first place.
It was actually a legacy as it served a particular purpose in our CI infra. As some projects out there are probably using it for the same purpose, we plan to remove it along with the refactor of `build_args` to make the usage more intuitive.

**Comment by bluesource** [comment]
Sorry for writing further comments on this closed issue but I seams to be the only issue referencing this topic.

I think the behavior before this commit https://github.com/grab/cocoapods-binary-cache/commit/b18577b3c8b7a7396c6201033b521a9488c6d817 was correct. 

Building the library without evolution support seams to have major drawbacks. 
For example:
I want to generate the cache in the CI, the CI is ie. still on XCode 12.2, some devs are already using 12.3 some are on 12.2.
The cache is unusable for user with 12.3.

Without evolution support the shared cache becomes useless in bigger teams. :(

**Comment by trinhngocthuyen** [comment]
Hi @bluesource, if you wish to enable library evolution, you can just either:
- Set the build setting `BUILD_LIBRARY_FOR_DISTRIBUTION` inside the `post_install` hooks of the Podfile.
- Set it via the `build_args` option in `config_cocoapods_binary_cache`.

The former is recommended as `build_args` is yet to be refactored.

Also, an alternative for your case is to have multiple cache repos for multiple Xcode versions. Please refer to [this doc](https://github.com/grab/cocoapods-binary-cache/blob/master/docs/configure_cocoapods_binary_cache.md#configure-cocoapods-binary-cache) for the multi-cache-repo config
```rb
config_cocoapods_binary_cache(
  cache_repo: {
    "default" => { ... } # <--- xcode 12.2
    "xcode12.3" => { ... }
  }
)
```
As for our infra, we use different cache repos for CI and local, for Xcode 11 and Xcode 12 :)

**Comment by bluesource** [comment]
@trinhngocthuyen 
Thanks alot for your help!

I try using BUILD_LIBRARY_FOR_DISTRIBUTION for now :)
