### ISSUE TITLE
Unexpected 'Pods.xcodeproj' is kept shown after 'pod binary prebuild'

### ISSUE THREAD

**Issue by innocarpe** [grab/cocoapods-binary-cache#56]
### Checklist

- [x] Updated the plugin to the latest version
- [x] I've read the [Contribution Guidelines](https://github.com/grab/cocoapods-binary-cache/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/grab/cocoapods-binary-cache/issues)

#### Command executed

```bash
$ pod binary prebuild
```

#### What went wrong?

I recently migrated my project's cocoapods-binary from [leavez/cocoapods-binary](https://github.com/leavez/cocoapods-binary) to this, and I found some weird issue after migration. After `pod binary prebuild`, Unexpected `Pods.xcodeproj` is seems to be created to my `xcworkspace` like below. 

It says the path is `_Prebuild/Pods.xcodeproj` but there are only `GeneratedFrameworks` folder and `Manifest.lock` file 🤔 (The path of right Pods.xcodeproj is `Pods/Pods.xcodeproj` as I expected)

<img width="250" alt="Screen Shot 2021-01-18 at 9 22 32 PM" src="https://user-images.githubusercontent.com/2222333/104915908-a6203700-59d4-11eb-9d33-2920337ebaf4.png"> <img width="258" alt="Screen Shot 2021-01-18 at 9 22 41 PM" src="https://user-images.githubusercontent.com/2222333/104915903-a4567380-59d4-11eb-9f70-adebbf29c31a.png"> 

How can I handle this issue not to create this unwanted `Pods.xcodeproj`? Thanks! :)

#### Plugin version

<details><pre> 0.1.11 </pre></details>

#### Installed CocoaPods plugins

<details><pre> cocoapods 1.10.1 / cocoapods-binary-cache </pre></details>

**Comment by trinhngocthuyen** [comment]
Actually, the `Pods.xcodeproj` under the `_Prebuild` is created when prebuilding frameworks. It particularly serves the internal logic to prebuild frameworks (by `pod binary prebuild`).
The presence of this xcodeproj does not affect the main project at all. That means, your workspace still functions properly as usual... For now, despite it being added to the workspace, you can just ignore it, or delete it from the workspace :)

As for improvements, we'll try to intercept the workspace generation and exclude this xcodeproj.

**Comment by innocarpe** [comment]
Thanks for the comment.

Yeah it has no bad effect on our workspace as you said. But we're using xcodegen to manage the project and we often execute project-create script after fetch master branch, means that this `Pods.xcodeproj` is continuously created even if I remove it 😭) 

It'll be glad to exclude the `Pods.xcodeproj` in the future 😄

**Comment by trinhngocthuyen** [comment]
The issue has been fixed in https://github.com/grab/cocoapods-binary-cache/commit/e29c42ce87aea8db2f9f8a07ca37953e3a03d472. Kindly check this out. You probably need to remove the xcworkspace (once) prior to running the CLI again.

**Comment by innocarpe** [comment]
@trinhngocthuyen Thanks for the patch!! 🙏 
Do you have any scheduled next release? We'll updated this library right after the next release 😄

**Comment by innocarpe** [comment]
And it works!

**Comment by trinhngocthuyen** [comment]
Included in [0.1.13](https://github.com/grab/cocoapods-binary-cache/releases/tag/0.1.13)
