### ISSUE TITLE
[Question] S3 support

### ISSUE THREAD

**Issue by dcacenabes** [grab/cocoapods-binary-cache#59]
### Checklist

- [x] I've read the [Contribution Guidelines](https://github.com/grab/cocoapods-binary-cache/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/grab/cocoapods-binary-cache/issues) if there was such a request before.

#### Motivation

<details><pre>More choice for users</pre></details>

#### Summary

<details><pre>More than a feature request, this is a question. I noticed than in your documentation on how the system works you mention that caches can be stored in git but also in S3: https://github.com/grab/cocoapods-binary-cache/blob/master/docs/how_it_works.md . I could not find any other reference in all the docs regarding S3. Is it actually supported at all? Is there any way we can use S3 instead of a git remote repository?</pre></details>

**Comment by trinhngocthuyen** [comment]
Hi @dcacenabes,
Thanks for reaching out!
Probably the documentation is a bit confusing as it describes the general ideas. Also, this doc is a bit outdated as we have split some steps in the original diagram to offer more workflows.

To answer your question, currently, s3 is not yet supported. However, you still can configure s3 together with the plugin this way:
- Use local cache directory by not specifying the `remote` field in the `cache_repo` option. Refer to https://github.com/grab/cocoapods-binary-cache/issues/31#issuecomment-727288716 for the sample config.
- Write your own tool/script to fetch the cache from s3 to this local cache directory.  The same happens to the upload to s3 (ie. handled by your own tool/script)

Then, the workflow of a normal installation should be like this:
```sh
fetch_from_s3 # <-- your own tool/script, to fetch from s3 to local cache directory
pod binary fetch
pod install
```

**Comment by dcacenabes** [comment]
Thank you for the clarification!
