### ISSUE TITLE
Changing pod version doesn't update the binary

### ISSUE THREAD

**Issue by qalandarov** [grab/cocoapods-binary-cache#6]
When updating a pod version and running `pod binary-cache --cmd=prebuild` the binary is not updated (I observed this behavior with `cocoapods-binary` plugin, but since you're listening to its hooks and manipulating the files I thought you could address this)

Steps to reproduce:
1. Have a basic podfile with `pod 'MBProgressHUD', '1.1.0', :binary => true` and run `pod binary-cache --cmd=prebuild`
2. Bump the version to `1.2.0` and run the above command again (also observed for downgrading the version)
3. The manifest gets updated, but not binary

**Comment by bigbangvn** [comment]
Thanks @qalandarov let me check and get back to you

**Comment by trinhngocthuyen** [comment]
Hi @qalandarov, sorry for the delayed update.
I believe this issue has been resolved as we added a validation layer between Podfile and the prebuilt manifest. Please check out the latest release.

Kindly note that:
- There have been various changes in how we configure the lib as well as the CLI syntax. Refer to [Configure Podfile](https://github.com/grab/cocoapods-binary-cache/blob/master/README.md#2-configure-podfile) and [CLI](https://github.com/grab/cocoapods-binary-cache/blob/master/README.md#3-cli) for more details
- However, when running `pod update AFramework`, the binary could be incorrectly integrated. This is one of our roadmap items to work on in the future
