### ISSUE TITLE
[Question] Pods Sources Workflow

### ISSUE THREAD

**Issue by savage7** [grab/cocoapods-binary-cache#63]
I just have a basic workflow question :blush:

Before using this plugin I commited the Pods folder to git.
* This speeds up the pod install alot
* It gives me the safety that the used sources don't change and that I have a copy of the Pods source
* I already had this like "deleted git repos"

How do you handle this with this plugin? I still build from source in the CI, exactly as you have it in the example project.

What I currently do:
I copy the sources to a folder called **PodSources** on the CI I move to **Pods**. Then I call `pod install.`
However this is a bit complicated and error prone...

**Comment by trinhngocthuyen** [comment]
For us, we ignore Pods folder from git.

The cons of committing Pods to git is: it increases the repo size which hurts the git fetch/push processes. Also, the pull requests/merge requests (if having frameworks update) have a lot of irrelevant changes.

About the speed up you mentioned, I'd say it only helps with the fresh pod installation. In the subsequent runs, CocoaPods performs incremental installations which should be fast. Also, even with the fresh installation, CocoaPods also have caches in place to reduce the time it takes.

Regarding the point about sources staying unchanged, we try to explicitly declare pod versions in Podfile instead :)

My personal recommendation is that we should exclude Pods from git. But it's up to you to decide.
In case you stay firm on having Pods committed to the repo, you can ignore the prebuilt frameworks added to the pod folder. Those frameworks are placed under `<PodName>/_Prebuilt`. However, please be noted that other CocoaPods plugins could possibly modify pod folders and you may end up doing the same for such cases.

Hope those above could help you clear your doubts. Thank you!

**Comment by savage7** [comment]
@trinhngocthuyen 
Thanks a lot for your help & feedback! I'll try to remove the sources completely and monitor how our CI builds change.
