### ISSUE TITLE
I can not prebuild the frameworks  successfully

### ISSUE THREAD

**Issue by MuYuLi** [grab/cocoapods-binary-cache#71]
![image](https://user-images.githubusercontent.com/16809810/111305282-b3366b00-8691-11eb-90f2-d10007278d78.png)
I set the config like this in Podfile
then "pod install"
but the result was not what I wanted
![image](https://user-images.githubusercontent.com/16809810/111305719-41aaec80-8692-11eb-941d-c02e0a0ee297.png)

**Comment by trinhngocthuyen** [comment]
> but the result was not what I wanted

Could you please describe the behavior you expected?

Do note that the command to prebuild frameworks is `pod binary prebuild`. Kindly refer to https://github.com/grab/cocoapods-binary-cache#3-cli for reference

**Comment by bharathns** [comment]
pod binary prebuild does not work i have installed gem install cocoapods-binary-cache
