### ISSUE TITLE
Xcodebuild don't work on generate_multiple_pod_projects => true in podfile

### ISSUE THREAD

**Issue by Deltarys** [grab/cocoapods-binary-cache#76]
Hi !! i love your work, its really helpful and time saving
But recently we add this option in our podfile `generate_multiple_pod_projects => true`
this cause xcodebuild not work and stop making pods build

my podfile:

```
plugin "cocoapods-binary-cache"
use_frameworks!
platform :ios, '13.0'
workspace 'TestProject.xcworkspace'

install! 'cocoapods', :generate_multiple_pod_projects => true

config_cocoapods_binary_cache(
  cache_repo: {
    "default" => {
      "local" => "~/.cocoapods-binary-cache/prebuilt-frameworks2",
      "device_build_enabled" => "true",
    }
  }
)

target 'TestProject' do
  pod 'Alamofire', '~> 5.2', :binary => true
  pod 'AFNetworking', '~> 4.0', :binary => true
  pod 'SDWebImage', '~> 5.0', :binary => true
  pod 'MBProgressHUD', '~> 1.2.0', :binary => true
  pod 'Masonry', :binary => true
  pod 'SwiftyJSON', '~> 4.0', :binary => true
  pod 'SVProgressHUD', :binary => true
  pod 'MJRefresh', :binary => true
  pod 'CocoaLumberjack/Swift', :binary => true
  pod 'SnapKit', '~> 5.0.0', :binary => true
  pod 'Kingfisher', '~> 6.0', :binary => true
  pod 'RxSwift', '6.1.0', :binary => true
  pod 'RxCocoa', '6.1.0', :binary => true
  pod 'Firebase/Crashlytics', '6.31.1', :binary => true
  pod 'Firebase/Analytics', '6.31.1', :binary => true
  pod 'Firebase/Core', '6.31.1', :binary => true
  pod 'GoogleTagManager', '7.1.3', :binary => true
end
```

xcode build try to do:

`$ xcodebuild -project /_Prebuild/Pods.xcodeproj -target AFNetworking -target Alamofire -target CocoaLumberjack -target FirebaseCore -target FirebaseCoreDiagnostics -target FirebaseCrashlytics -target FirebaseInstallations -target GoogleDataTransport -target GoogleUtilities -target Kingfisher -target MBProgressHUD -target MJRefresh -target Masonry -target PromisesObjC -target RxCocoa -target RxRelay -target RxSwift -target SDWebImage -target SVProgressHUD -target SnapKit -target SwiftyJSON -target nanopb -configuration Release -sdk iphonesimulator -destination id=177D1EE9-B0E9-483A-BF34-A3295A410870 ARCHS=x86_64 ONLY_ACTIVE_ARCH=NO build 2>&1`

this is a test project just to measure build times

i checked your docs about how configure the plugin, but don't find anything, its there something im missing ??
many thanks !!

**Comment by trinhngocthuyen** [comment]
I believe this plugin currently assumes that there is only one project for all pods 😄. This is not yet handled

**Comment by Deltarys** [comment]
Yikes !!
many thanks for the answer, lets close this issue then.

**Comment by Buju77** [comment]
hi, we are currently also using `generate_multiple_pod_projects` ... would this be something to easily add support to?
