### ISSUE TITLE
How to configure and generate static library？

### ISSUE THREAD

**Issue by xuwenxindeai** [grab/cocoapods-binary-cache#87]
### Checklist

- [ ] I've read the [Contribution Guidelines](https://github.com/grab/cocoapods-binary-cache/blob/master/CONTRIBUTING.md)
- [ ] I've searched for [existing GitHub issues](https://github.com/grab/cocoapods-binary-cache/issues) if there was such a request before.

#### Motivation

<details><pre>[Details go here]</pre></details>

#### Summary

<details><pre>[Details go here]</pre></details>

**Comment by trinhngocthuyen** [comment]
Sorry for the late response.

This plugin prebuilds frameworks based on its build settings in the Pods project. Whether a framework is built as a static or dynamic framework is not within the plugin's scope.

A very common way to achieve it is to change the `:linkage` attr (in `Pod::BuildType`) of a pod to `:static`.
Or, if you prefer a plugin, this [cocoapods-pod-linkage](https://github.com/microsoft/cocoapods-pod-linkage) is possibly what you need.
