### ISSUE TITLE
A framework includes statically linked binaries cannot output binary well

### ISSUE THREAD

**Issue by lixiaoyu** [grab/cocoapods-binary-cache#9]
I have a framework that contain statically linked binaries, after prebuild,it emit error like this:
> [!] The 'Pods-PodBinCacheExample' target has transitive dependencies that include statically linked binaries: (/Users/xx/Desktop/CICD/cocoapods-binary-cache/PodBinaryCacheExample/Pods/xxx/Vendor/LAME/libmp3lame.a, /Users/xx/Desktop/CICD/cocoapods-binary-cache/PodBinaryCacheExample/Pods/xxx/Vendor/Speex/Speex.framework, and /Users/xx/Desktop/CICD/cocoapods-binary-cache/PodBinaryCacheExample/Pods/xxx/Vendor/OpusCodec.framework)

**Comment by trinhngocthuyen** [comment]
Hi @lixiaoyu,

As I know, this is actually the known validation from CocoaPods instead.

There are a few threads in CocoaPods repo mentioning this issue. You can check them out here: https://github.com/CocoaPods/CocoaPods/issues/7234, https://github.com/CocoaPods/CocoaPods/issues/6889

**Comment by lixiaoyu** [comment]
@trinhngocthuyen  oh, thanks for your information,i will try

**Comment by bigbangvn** [comment]
@lixiaoyu can you help to verify whether it happen if disable the plugin?

**Comment by lixiaoyu** [comment]
@bigbangvn the framwork works well if we intergrate it with source code,say don't use the plugin to output binary.
 I try the solution mentioning in cocoapods issues, add 'static_framework = true' in my podspec file, but some other issues occurred

**Comment by bigbangvn** [comment]
@lixiaoyu Do you have the sample project that reproduces the issue?

**Comment by nannanIT** [comment]
@lixiaoyu hi, have you resolved this problem?

**Comment by trinhngocthuyen** [comment]
Hi folks, I am closing this issue as the *transitive dependencies* validation actually comes from CocoaPods, and not specific to the plugin.
Kindly revise the project dependencies as this validation **prevents dynamic frameworks depending on static frameworks**.

Thank you!
