### ISSUE TITLE
Azure Pipeline

### ISSUE THREAD

**Issue by shahzadmajeed** [grab/cocoapods-binary-cache#96]
Hi,

Git clone fails in azure pipeline because it is a private/internal repository for cache. Is there a way to specify ssh key etc.. in the script itself or does that need to be done on CI side? Also, I'm curious of someone have tried Azure with cocoapods-binary-cache plugin.

Btw, I love this plugin. The concept is amazing!

-Shahzad

**Comment by trinhngocthuyen** [comment]
To the best of my knowledge, Azure, Gitlab, or any CI/CD provider does support https clone with an access token (can be either a personal access token, or job access token). I think you can use it for CI jobs.

In the case of Gitlab, the url would be something like this: 
```
https://gitlab-ci-token:$CI_JOB_TOKEN@<host_name>:<path/to/project>.git
```
I believe there is a similar usage in Azure pipelines
